### ISSUE TITLE
setActiveIndexByID()!!

### ISSUE THREAD

**Issue by NiteMugGoo** [scaleflex/js-cloudimage-360-view#73] opened 2021-04-20 03:59 UTC
I want to display the thumbnails outside of div.mercedes-360-view and arbitrarily display the selected image at any given time.

In other words, I want setActiveIndexByID().

Is that possible for you?

Best regards.

**Comment by NiteMugGoo** [comment] 2021-04-20 08:49
For now, I have achieved this with the following:
```<script` src="https://cdn.scaleflex.it/plugins/js-cloudimage-360-view/2.6.0/js-cloudimage-360-view.min.js"></script>
<script>
function setActiveIndexByID(id) {
	let currentViewer = window.CI360._viewers[0];
	if (currentViewer) {
		let isForword = (currentViewer.activeImage-1 > id-1);
		while (true) {
			if (isForword) {
				currentViewer.next();
			} else {
				currentViewer.prev();
			}
			if (currentViewer.activeImage-1 == id-1) {
				break;
			}
		}
	}
}
window.CI360.setActiveIndexByID = setActiveIndexByID;
</script>```
If I have any mistakes, please teach me.
regards,

**Comment by amrw-js** [comment] 2022-01-26 18:33
hey @NiteMugGoo, sure we added this enhancement to our roadmap. 
duplicate of #83

**Closed by amrw-js** 2022-01-26 18:33 UTC
Labels: duplicate
