### ISSUE TITLE
autoplay on mobile and table devices

### ISSUE THREAD

**Issue by jinncore** [scaleflex/js-cloudimage-360-view#85] opened 2021-06-30 19:49 UTC
Hello, very good library! 
Please tell me, is there any way to run data-autoplay on mobile and tablet devices?

**Comment by amrw-js** [comment] 2021-11-04 12:02
Duplicate of [#42 ](https://github.com/scaleflex/js-cloudimage-360-view/issues/42)

**Closed by amrw-js** 2021-11-04 12:02 UTC
