### ISSUE TITLE
incorrect work in a modal window

### ISSUE THREAD

**Issue by DenysRoshchin** [scaleflex/js-cloudimage-360-view#68] opened 2021-03-08 19:25 UTC
Thank you very much for this great plugin, it is very useful and easy to use. But I found the incorrect behavior when I used it in a modal popup. Firstly, it starts only if I selected the autoplay mode, secondly, the rotation speed is applied only if the page has not yet been fully loaded and I have already opened the modal window, but if I open the modal window after the page has fully loaded, the rotation speed is not applied ... Maybe someone came across a similar one?

**Comment by amrw-js** [comment] 2021-11-04 12:00
Duplicate of [#48](https://github.com/scaleflex/js-cloudimage-360-view/issues/48)

**Closed by amrw-js** 2021-11-04 12:00 UTC
