### ISSUE TITLE
How to reinit elements after ajax or fetch loading?

### ISSUE THREAD

**Issue by Venegrad** [scaleflex/js-cloudimage-360-view#61] opened 2021-02-16 01:01 UTC
I have a problem. Some content im getting by ajax. And after, 360 plugin wont show. Im trying to reinit plugin `window.CI360.init()` or destroy, but thats not working.  If element 360 is hidding (like in modal), and im show modal first image not showing.

![image](https://user-images.githubusercontent.com/9676703/108006106-361cc500-7003-11eb-8bc7-6d54ce0c10be.png)

**Comment by dzmitry-stramavus** [comment] 2021-02-26 07:14
@Venegrad , I'll check this during the week.

**Comment by Realmaker** [comment] 2021-02-26 16:03
Works for me. But can I destroy and init the 360 Tool for a special div only? I have multiple insances on the page an like to integrate a color selection for these several elements.

**Comment by amrw-js** [comment] 2021-11-04 11:57
Duplicate of [#48](https://github.com/scaleflex/js-cloudimage-360-view/issues/48)

**Closed by amrw-js** 2021-11-04 11:57 UTC
Labels: bug, duplicate
